# Generated by Django 5.0.7 on 2024-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryModel',
            new_name='Country',
        ),
    ]
