# Generated by Django 5.0.7 on 2024-08-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_countryembassyappointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryembassyappointment',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AddField(
            model_name='countryidentity',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AddField(
            model_name='countryinterview',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AddField(
            model_name='countryofferletter',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AlterField(
            model_name='countryembassyappointmentcontent',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AlterField(
            model_name='countrysubmitinitialducuments',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
        migrations.AlterField(
            model_name='countrysubmitinitialducumentscontent',
            name='title',
            field=models.CharField(default='need to change title', max_length=255),
        ),
    ]
