# Generated by Django 5.0.7 on 2024-08-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutuscontentimage_aboutuscontents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='jobs_found_count',
        ),
    ]
