# Generated by Django 5.0.7 on 2024-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_remove_aboutus_jobs_found_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='jobs_found_count',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
