# Generated by Django 5.0.7 on 2024-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('post_image', models.ImageField(default='blogs/post_img/post.jpg', upload_to='blogs/post_img')),
                ('author', models.CharField(max_length=200)),
                ('author_image', models.ImageField(default='blogs/author_img/author.jpg', upload_to='blogs/author_img')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkind_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
