# Generated by Django 5.0.7 on 2024-08-23 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
