# Generated by Django 5.0.7 on 2024-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contactform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfirstcontent',
            name='title_one',
            field=models.CharField(default='need to change title_one', max_length=255),
        ),
        migrations.AddField(
            model_name='contactfirstcontent',
            name='title_two',
            field=models.CharField(default='need to change title_two', max_length=255),
        ),
    ]
