# Generated by Django 5.0.7 on 2024-08-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_contactfirstcontent_title_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsecondcontents',
            old_name='content',
            new_name='title',
        ),
    ]
