# Generated by Django 5.0.7 on 2024-08-13 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('jobtypes', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], max_length=2, verbose_name='Job Type')),
                ('joblevel', models.CharField(choices=[('JR', 'Junior'), ('ML', 'Mid-level'), ('SR', 'Senior'), ('EX', 'Executive')], max_length=2, verbose_name='Job Level')),
                ('position', models.CharField(db_index=True, max_length=255, verbose_name='Position')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('jobtitle', models.CharField(db_index=True, max_length=255, verbose_name='Job Title')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrymodel', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['jobtitle', 'position'],
                'indexes': [models.Index(fields=['jobtitle'], name='job_jobsmod_jobtitl_618422_idx'), models.Index(fields=['position'], name='job_jobsmod_positio_76b1ec_idx')],
                'unique_together': {('jobtitle', 'position')},
            },
        ),
    ]
