# Generated by Django 5.0.7 on 2024-08-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='status',
            field=models.CharField(choices=[('PU', 'PUBLISHED'), ('UN', 'UNPUBLISHED')], db_index=True, max_length=255, null=True, verbose_name='Status'),
        ),
    ]
