# Generated by Django 5.0.7 on 2024-08-15 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_countryembassyappointment_and_more'),
        ('job', '0002_jobsmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('jobtypes', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], max_length=2, verbose_name='Job Type')),
                ('joblevel', models.CharField(choices=[('JR', 'Junior'), ('ML', 'Mid-level'), ('SR', 'Senior'), ('EX', 'Executive')], max_length=2, verbose_name='Job Level')),
                ('position', models.CharField(db_index=True, max_length=255, verbose_name='Position')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company_name', models.CharField(max_length=255)),
                ('vacancy', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exprience', models.CharField(max_length=255)),
                ('valid_until', models.DateTimeField()),
                ('education', models.CharField(max_length=255)),
                ('responsibilities', models.TextField(blank=True, max_length=500, null=True)),
                ('requirements', models.TextField(blank=True, max_length=1000, null=True)),
                ('preferred_qualifications', models.TextField(blank=True, max_length=500, null=True)),
                ('why_join_us', models.TextField(blank=True, max_length=500, null=True)),
                ('jobtitle', models.CharField(db_index=True, max_length=255, verbose_name='Job Title')),
                ('status', models.CharField(choices=[('PU', 'PUBLISHED'), ('UN', 'UNPUBLISHED')], db_index=True, max_length=255, null=True, verbose_name='Status')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='JobsModel',
        ),
    ]
