# Generated by Django 5.0.7 on 2024-08-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_countryembassyappointment_and_more'),
        ('job', '0003_jobs_delete_jobsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Education_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='exprience',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='joblevel',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jobtypes',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='position',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='status',
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/job/company_cover_pic/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/job/company_profile_pic/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_category'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_education_level'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_level'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Job_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_location'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Job_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_status'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_type'),
        ),
    ]
