# Generated by Django 5.0.7 on 2024-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category_job_education_level_job_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='Job_Status',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Job_Location',
            new_name='job_location',
        ),
        migrations.AlterField(
            model_name='job_education_level',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Job_Status',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(choices=[('PU', 'Published'), ('UN', 'Unpublished')], db_index=True, default='PU', max_length=2, verbose_name='Status'),
        ),
    ]
